alphagov/forms-prototypes

- app/routes.js
- app/views/form-designer/edit-page.html
- app/views/form-designer/form-index.html
- lib/utils.js
Adds a 'Delete page' button to the Edit page view. There isn't currently any confirmation step for deletion - once you click the button there's no going back.
Fixes #4
> Add delete button to Edit page

- app/views/publisher/form-summary.html
- app/views/publisher/versions.html
Some changes made for the simpleish versioning mini-spike. I will merge these once people have reviewed the spike and are happy with it.
> Add version list

- app/data/session-data-defaults.js
- app/views/form-designer/check-answers-page-preview-new-tab.html
- app/views/form-designer/check-answers-page-preview.html
- app/views/form-designer/edit-confirmation-page.html
- app/views/form-designer/edit-page.html
- app/views/form-designer/form-create-a-form.html
- app/views/form-designer/form-home.html
- app/views/form-designer/form-index.html
> Small content updates

- app/views/form-designer/form-index.html
Fixes #32 
- [N/A] I've written unit tests for these changes (if code change)
- we're not currently testing this prototype
- [N/A] I've updated the documentation in (If any documentation requires updating)
> Fix page numbering off-by-one error (#32)

- app/views/form-designer/form-create-a-form.html
- app/views/form-designer/form-home.html
- app/views/form-designer/page-preview-new-tab.html
> Fix new tab preview 

- app/views/form-designer/edit-check-answers-page.html
Content changes made, aligning with other edit pages.
Updated in page preview section to replicate other edit pages.
Added back link
> Update content and page layout to align with other edit pages

- app/views/form-designer/page-preview-new-tab.html
- app/views/form-designer/page-preview-placeholder.html
- app/views/form-designer/page-preview.html
> Fix keyboard navigation issue in new tab preview

- app/data/returning-session-data-defaults-a11y.js
- app/data/returning-session-data-defaults.js
Remove declaration and what happens next for testing round
> Remove declaration and what happens next for testing round

- app/data/returning-session-data-defaults-a11y.js
- app/data/returning-session-data-defaults.js
- app/routes.js
Fix completed tag bugs on CYA and confirmation edit page
s
> Fix completed tag bugs on CYA and confirmation edit pages

- app/views/form-designer/create-form.html
Improved two section headings and text of one link to make them more specific.
> Content tweaks to task list headings and link text

- app/routes.js
- app/views/form-designer/create-form.html
- app/views/form-designer/page-preview-new-tab.html
- app/views/form-designer/provide-support-details.html
I believe this is now done. Content changes have been added
> 125 add new journey provide contact details for support

- app/routes.js
- app/views/form-designer/create-form.html
- app/views/form-designer/edit-check-answers-page.html
> (fix) Declaration is optional, so no errors if empty

- app/config.js
- app/data/returning-session-data-defaults-a11y.js
- app/data/returning-session-data-defaults.js
- app/routes.js
- app/views/form-designer/are-you-sure-you-want-to-edit-live-questions.html
- app/views/form-designer/check-answers-page-preview-new-tab.html
- app/views/form-designer/completed-forms-email/add-confirmation-code.html
- app/views/form-designer/completed-forms-email/set-completed-forms-email.html
- app/views/form-designer/confirmation-page-preview-new-tab.html
- app/views/form-designer/create-form.html
- app/views/form-designer/delete.html
- app/views/form-designer/edit-answer-type.html
- app/views/form-designer/edit-check-answers-page.html
- app/views/form-designer/edit-confirmation-page.html
- app/views/form-designer/edit-page.html
- app/views/form-designer/form-home.html
- app/views/form-designer/form-index.html
- app/views/form-designer/form-is-live.html
- app/views/form-designer/form-list-a11y.html
- app/views/form-designer/form-list.html
- app/views/form-designer/make-your-form-live.html
- app/views/form-designer/page-preview-new-tab.html
- app/views/form-designer/provide-link-to-privacy-information.html
- app/views/form-designer/provide-support-details.html
- app/views/form-designer/signon/dashboard.html
- app/views/form-designer/signon/sign-in.html
- app/views/layout-govuk-forms.html
- lib/prototype-admin/show-data.html
- package-lock.json
A few things have been missed when making changes to the prototype, and have caused confusion or issues in testing meaning we might not be getting a fully representative experience at the time of testing. 
Added bits we missed that should have been done as general maintenance so we didn't get feedback on known issues or fixed designs. 
Also added basic "sign out" account stuff for future testing to begin.
Added ability to make questions optional.
Some areas have been aligned with the development version so we can minimise impact of the differences in UR... this has raised some inconsistencies that I think means it would be good to do a quick review of where the product is compared with what we actually want it to look like (the prototype?).
> 141 prototype clean up november 2022

- app/views/form-designer/create-form.html
- app/views/form-designer/form-index.html
- app/views/form-designer/make-your-form-live.html
Correcting link text and aligning with production.
> Content tweaks

- app/routes.js
- app/views/form-designer/completed-forms-email/add-confirmation-code.html
- app/views/form-designer/completed-forms-email/change-email-address.html
- app/views/form-designer/completed-forms-email/confirmation-code-expired.html
- app/views/form-designer/completed-forms-email/confirmation-code-sent.html
- app/views/form-designer/completed-forms-email/email-confirmation.html
- app/views/form-designer/completed-forms-email/set-completed-forms-email.html
- app/views/form-designer/create-form.html
added email given to the task list page
if user changes email, task list will keep the current "verified" email
once new email is verified it becomes the current email
tags should act appropriately, but might miss some nuance
> 144 add current form submission email to task list page

- app/views/index.html
- app/views/working/index.html
- app/views/working/numbering-questions-list/data.js
- app/views/working/numbering-questions-list/your-questions-a.html
- app/views/working/numbering-questions-list/your-questions-b.html
- app/views/working/numbering-questions-list/your-questions-c.html
- app/views/working/numbering-questions-list/your-questions-d.html
- app/views/working/numbering-questions-list/your-questions-e.html
Added a few versions to consider moving into testing
> Adding examples of question list page views. Nav included

- app/routes.js
- app/views/form-designer/pages/edit-settings.html
- app/views/form-designer/pages/edit.html
- app/views/form-designer/preview/check-answers.html
- app/views/form-designer/preview/page.html
Add a setting for select answer type to be able to choose 'none of the above' from the list.
If answer type is select from list, then the question cannot be optional.
> Add select from list settings

- app/routes.js
I've missed removing the commented out code in routes.js in the previous PR. Ooopsie 😅
> Quick fix for left out uncommented code in routes

- app/views/form-builder-prototypes.html
- app/views/index.html
Updated the content of the main index pages to better reflect the prototypes and make it clearer what things are.
> Tidied content in index pages

- app/routes.js
Small tweaks for consistency and style.
> Tweaks to notification banner messages

- app/assets/sass/product-page.scss
- app/assets/sass/product/_tasklist.scss
- app/views/product-pages/index.html
- app/views/product-pages/signup/features.html
- app/views/product-pages/signup/get-started.html
- app/views/product-pages/signup/index.html
- app/views/product-pages/signup/subscribe.html
- app/views/product-pages/signup/support.html
see https://docs.google.com/document/d/1J4hi4nujbKoA2rcdqWqZzp3aTPV87iIclPHP5W-mwW4/edit
Trello: https://trello.com/c/PW14lC2X/864-make-landing-pages-for-signing-in-to-govuk-forms-for-user-research-of-trial-user-and-auth0
> Add signup product page prototype

- package-lock.json
- package.json
This adds Laurence’s fix to the markdown plugin
> Rebase to start preview work

- app/assets/sass/product-page.scss
- app/routes.js
- app/views/form-designer/pages/_routes.js
- app/views/form-designer/pages/check-question.html
- app/views/form-designer/pages/preview-question.html
- app/views/form-designer/partials/status-draft-form.html
- app/views/form-designer/partials/status-live-form.html
- app/views/form-designer/preview/check-answers.html
- app/views/form-designer/preview/confirmation.html
- app/views/form-designer/your-forms.html
- app/views/form-designer/your-questions.html
- package-lock.json
- package.json
https://forms-prototypes-pr-209.herokuapp.com/
* Updated packages to use new [version 5 of the frontend](https://frontend.design-system.service.gov.uk/changes-to-govuk-frontend-v5/#changes-to-gov-uk-frontend-v5-0-0) 
* Fixed URL issues off the back of the update
* Updated task list to use the nunjucks 
* Updated tags to new colours and text
* Fixed incorrect heading classes being used
* Added delete draft form functionality
* for future rounds of testing it makes sense to stay closely aligned with the development environment which has recently gone through the frontend update
* it will help design continue to communicate effectively with developers when updating to new patterns
> 2023 12 15 update frontend

- app/data/session-data-defaults.js
- app/views/form-designer/pages/check-question.html
- app/views/form-designer/pages/edit.html
These are just a few updates to content to match what we have in production now. 
It also includes one update to content for the optional question setting that is not yet implemented in production but is in the backlog to be. 
Primarily need Chris to review this - just to check I haven't broken anything. 
Trello card for this:https://trello.com/c/ObHw2LYg/1291-content-for-previews-of-an-individual-question-and-review-latest-content-in-the-prototype
The Trello card includes a link to this doc with more details about these changes: https://docs.google.com/document/d/1QlzCLyoBq0UGqbekcsfnRZEAcZtmlEOUqBN_kYPltHc/edit?usp=sharing
> Update content to align it with production

- app/views/product-pages/group-admin/tasklist-activegroup.html
- app/views/product-pages/group-admin/tasklist-trialgroup.html
Task list pages for a trial group and active group
> Adding tasklist pages

- app/views/product-pages/org-admin/add-groupadmin-and-editor.html
> Adding 1 file to org admin

- app/views/product-pages/group-admin/editmembers3.html
- app/views/product-pages/group-admin/editmembers4.html
- app/views/product-pages/group-admin/grouplanding.html
- app/views/product-pages/group-admin/grouplanding2.html
Added logic for when a user creates a form we show it in the landing page 1 and 2
> 08 04 2023 active group page changes
