alphagov/forms-prototypes

app/assets/sass/application.scss
app/views/form-builder-prototypes.html
app/views/publisher/confirm-email.html
app/views/publisher/declaration.html
app/views/publisher/email-confirmed.html
app/views/publisher/enter-email.html
app/views/publisher/form-summary.html
app/views/publisher/published.html
app/views/publisher/review-question.html
app/views/publisher/review.html
app/views/publisher/start.html

This adds an inital prototype for the approval and publishing workflow.
At present, it's not particularly interactive - you'll be able to navigate through the pages, and it will seem like you're going through a 'happy path' journey, but none of the text inputs will actually do anything.

Add initial static publisher prototype 

---

app/views/form-designer/edit-check-answers-page.html
app/views/form-designer/edit-confirmation-page.html
app/views/form-designer/edit-page.html

The preview shows unstyled content.
This is because the sandbox attribute was added to the iframe containing
the preview. sandbox prevents the iframe loading content from the same
origin and runninng scripts.
It's been changed to:
sandbox="allow-same-origin allow-scripts"
This doesn't provide much security - in our case we are not worried
about that, so it shouldn't matter unless we stop trusting the content
of the iframe at some point.

fix: in-page-preview stopped showing styling

---

app/views/form-designer/form-create-a-form.html
app/views/form-designer/form-index.html

Change the layout and text of the page list - both empty and when there are questions on it.

38 reorganise page list

---

app/data/session-data-defaults.js
app/routes.js
app/views/form-designer/form-create-a-form.html

Added error handling for form name screen -  if you don't put anything in the entry box, you get the errors.
There was no text for this so I made it up.

37 page list make the form name field mandatory and add error messages

---

app/views/form-designer/edit-page.html

- #41 
- #42 - Remove inline style height of the preview wrapper
- made using [MURAL](https://app.mural.co/t/gaap0347/m/gaap0347/1652082094071/bd86d8544291bd649aa003aa1c9a94576e730bc6?wid=0-1652083107773)

Page reorder and content changes as per MURAL

---

app/views/form-designer/check-answers-page-preview.html
app/views/form-designer/confirmation-page-preview.html
app/views/form-designer/page-preview-placeholder.html
app/views/form-designer/page-preview.html

Reduced/removed interactive elements from the in page preview iframes. 
This should cover:
- page-preview.html
- confirmation-page-preview.html
- check-answers-page-preview.html
- updated/fixed tab titles to match the heading of the page - not sure how big an impact this has, but could affect screen reader users
-

Remove interactivity of in page previews across journey

---

app/assets/sass/application.scss
app/assets/sass/patterns/_govuk-publishing-document-list.css
app/data/returning-session-data-defaults.js
app/routes.js
app/views/form-builder-prototypes.html
app/views/form-designer/form-list.html
lib/prototype-admin/show-data.html

All the design/copy in this commit has been made up to flesh out the pages and can all be changed.
Added a link under the `/form-builder-prototypes` page for a prototype of a return journey. 
The user is shown a list of forms they can edit, using the publishing component document list (for now).
When opening the first link, the data in `app/data/returning-session-data-defaults.js` is loaded into the session and the user is sent to the form overview page, which is populated with the data from the file.
A new section has also been added to the show data page linked in the footer. It shows the json output of the current form, which can be copied into the session file.

Add return journey prototype

---

app/routes.js
app/views/form-designer/delete.html
app/views/form-designer/edit-page.html
app/views/form-designer/form-create-a-form.html
app/views/form-designer/form-index.html

Closes #65, #66, #67
Linked to https://trello.com/c/BuQaxAYu/267-prototype-iterations-for-round-3-of-usability-testing-sprint-3-4
Added back buttons
User can change form name, even without questions added.
Button's have different text which changes if the question is being edited or is new.
I implemented a delete journey - a confirmation. I didn't include the question title on the delete confirm page because it was confusing to have two questions in it - Are you sure you want to delete the question "what is your name?"? We could easily add it back in for some context about what is being deleted.
The overview screen no longer uses the short form name - it does fall back to page number if the user hasn't put a question in.

Round 3 changes

---

app/views/form-designer/edit-page.html
app/views/form-designer/page-preview-new-tab.html
app/views/form-designer/page-preview.html

Also fix the 'Check your answers' flow for these types.
This will add them back to our prototype screen as well as the CSL deployment. Are we ok with having them in the prototype? If not I'll put them behind a feature flag and only show them in the CSL version.
in the check your answers screen:
In the new-tab preview:
and:

Add radios and checkboxes back

---

app/views/form-designer/check-answers-page-preview-new-tab.html
app/views/form-designer/form-create-a-form.html
app/views/form-designer/form-home.html
app/views/form-designer/form-index.html
app/views/form-designer/form-list-a11y.html
app/views/form-designer/form-list.html
app/views/form-designer/page-preview-new-tab.html

Closes #64 
In keeping with the initial proposal on #64 and the subsequent comments, this changes the page titles on the prototype as follows:
- Form builder home screen: 
- Current title: 'Form home'
- New title 'GOV.UK Forms'
- Form naming screen
- Current title: 'Create a form'
- New title 'What is the name of your form? - GOV.UK Forms'
- Form overview screen
- Current title: 'Form: {form title}'
- New title 'Form overview: {form title} - GOV.UK Forms'
- Create/Edit question page
- Current title: Uses the question title, e.g. 'What is your name?'
- New title '{question title} - GOV.UK Forms'
- New tab preview pages:
- Current title: 'Edit question'
- New title '{question title} - GOV.UK'
This should make it easier for users of some assistive technologies to navigate the prototype.

Add more consistent page titles to improve accessibility

---

app/views/form-designer/form-index.html

Fixes #63 
This change should make the prototype easier to work with for a user of disctation software
It includes a small visual change - the buttons now say 'Move up' and 'Move down' instead of 'Up ' and 'Down' respectively, and because of horizontal space constraints they they will always appear on a separate line from the 'Edit' link.
Their accessible names will be 'Move {{direction}} {{questionTitle}}' - e.g. 'Move up What is the name of your pet?', which should satisfy [WCAG criterion 2.5.3](https://www.w3.org/WAI/WCAG21/Understanding/label-in-name).
.

Improve accessible names of form overview actions

---

app/views/form-designer/page-preview-new-tab.html

The last page of the new-tab preview submit button says "Check your answers".
It's been changed to "Continue"
Old:
New:

Change continue button text on last page

---

app/views/form-designer/edit-page.html

Swap 'save' and 'preview' actions and make text reflect the use of them
more.
As the buttons now have longer text, they now occupy two rows at the standard text size.
Previous:
New:

Change edit-question button order, text

---

app/views/form-designer/page-preview-new-tab.html

Remove back button from first question in preview

---

app/views/form-designer/edit-page.html

On the edit page screen, the hint-text option should always be visible.
Kept the HR in.
Old:
New:

Move hint-text out of conditional-reveal

---

app/data/returning-session-data-defaults.js
app/views/form-designer/check-answers-page-preview-new-tab.html
app/views/form-designer/check-answers-page-preview.html
app/views/form-designer/edit-page.html
app/views/form-designer/page-preview-new-tab.html
app/views/form-designer/page-preview.html

Short name has been removed from the edit-question page and is no longer
used in any of the other pages.
The biggest visited change is in the CYA page, which used short name as
a heading for questions to be changed.
Short name was also used on pages with intro text (a feature that has
also been removed).
The best way to add short-name back to the prototype would be to revert
this commit.
Previous:
New:
URL's in the prototype haven't been altered to using the question stripped of spaces and punctuation as it would require a bigger change.

Remove short-name input field

---

app/views/form-designer/form-list-a11y.html
app/views/form-designer/form-list.html

Closes #78 
There's no visual change here, but here's what it looks like in the accessibility tree.

Add visually hidden text to edit links on forms list page

---

README.md
app/routes.js
app/views/form-designer/edit-page.html

During demonstrations we often have questions which could best be
answered with a number. The prototype originally had a numeric answer
type but it was removed to suport user testing sessions which did not
require it.
A feature flag has been added to enable a number answer type which
behaves like the short-text type.
To test it, start the prototype with the following command:
`ENABLE_NUMBER_ANSWER_TYPE=true npm run start`
With the feature enabled:
Without the feature enabled:

Add 'number' answer type

---

app/data/returning-session-data-defaults-a11y.js
app/data/returning-session-data-defaults.js
app/views/layout-govuk-forms.html

This change adds a 'restore default form data' link to the footer, which links to the return journey flow. This should make it easier to resolve the situation in research sessions where the user's data isn't reset for the return journey testing.
Also includes a small change to the return session data to prevent a bug - without this change the 'Add question' button will take you to edit one of the existing questions. the change looks bigger than it is because the files have been formatted.

Add 'restore default form data' link to footer

---

app/views/form-designer/check-answers-page-preview-new-tab.html

Closes #92 
Adds 'Not completed' text if the user hasn't answered the question in the preview.

Add dummy text to non-completed answers

---

app/views/form-designer/edit-page.html
app/views/form-designer/page-preview-new-tab.html
app/views/form-designer/page-preview.html

In CSL demos the answer type 'number' is the default selection for new questions.
This is because it was copied from the text type and uses the same logic to show that it's checked. Because it comes after the text type, it's always going to get selected.
This is fixed by introducing a new answer type 'number' and re-using the text code to display it in the previews.

Fix number type being selected in CSL

---

app/routes.js
app/views/form-designer/completed-forms-email/change-email-address.html
app/views/form-designer/completed-forms-email/confirmation-code-sent.html
app/views/form-designer/completed-forms-email/set-completed-forms-email.html
app/views/form-designer/form-index.html

This covers work required on https://github.com/alphagov/forms-prototypes/issues/98 
Includes 3 new pages:
- Set the email address for completed forms
- Are you sure you want to change this email address?
- Confirmation code sent
Added links to new journeys from form overview screen, and updated links to align with [MURAL](https://app.mural.co/t/gaap0347/m/gaap0347/1652697480711/fa60d6e36c472088d3c49ea4a7e7fc5b1d8186d4?wid=0-1657612670722)
Basic validation checks and errors for empty input or no radio selected.
Where user has entered an email before (in the same session) when they return to "Set the email address for completed forms" page and put a different email in they will be redirected to the "Are you sure you want to change this email address?" page.

Add "set email" journey w/ basic error checking. Inc form overview links

---

app/data/returning-session-data-defaults-a11y.js
app/data/returning-session-data-defaults.js
app/data/session-data-defaults.js
app/views/form-designer/confirmation-page-preview-new-tab.html
app/views/form-designer/confirmation-page-preview.html
app/views/form-designer/edit-confirmation-page.html

Iterated design for adding content on 'What happens next' to the confirmation page.
[Trello reference]( https://trello.com/c/x4GJbX3l)
> As a form creator, I need to add content about what happens next to a confirmation page, so the form submitter has clear expectations.
In general we have simplified the page and provided more guidance.
We have decided to remove editing the title for confirmation page message and keep it general.
Removed reference number as we won't be generating it.
Edit submitted form page has iterated design, where we include form name in the H1 hint text to be consistent.
We've included additional guidance on what this page is for and how form creators could include a useful content for 'What happens next' section.
We have removed default text and hint text in the …

103 design add content about what happens next to a confirmation page

---

app/routes.js
app/views/form-designer/completed-forms-email/add-confirmation-code.html
app/views/form-designer/completed-forms-email/confirmation-code-expired.html
app/views/form-designer/completed-forms-email/confirmation-code-sent.html
app/views/form-designer/completed-forms-email/email-confirmation.html
app/views/form-designer/completed-forms-email/set-completed-forms-email.html
app/views/form-designer/create-form.html
app/views/form-designer/edit-check-answers-page.html
app/views/form-designer/form-create-a-form.html
app/views/form-designer/form-home.html
app/views/form-designer/form-index.html

This gives us a starting point for trello card https://trello.com/c/qRUXjeHr/278-spike-explore-task-list-for-next-steps-in-publishing-form 
It is the first introduction of a task list pattern, with very basic functionality for now, to help us get feedback about steps in the publishing journey and being able to test the new set an email and confirm an email journeys. 
Note: still need to fix back link in the confirmation screen to go back to the task list page `create-form` instead of the overview page `form-index`

Start at task list within the service. Some links need updated

---

README.md
app/routes.js
app/views/form-designer/edit-page.html
app/views/form-designer/page-preview-new-tab.html
app/views/form-designer/page-preview.html

User need and hypothesis is in the  [Add number and long text answer
](https://github.com/alphagov/forms-prototypes/issues/107)
Added a textarea and number as a type of answer to the Add/Edit question page
Updated the format in the both previews
As a bonus added more hint-text to all answer types, so that we can test if it's helps form creators choose the answer they expect to get
Removed setting and displaying the character count for textarea to keep it simple for now.
The answer for a number follows guidance from GOV.UK Design System, to keep it as ` type="text'` and include additional parameters for
`inputmode: "numeric",
pattern: "[0-9]*",
spellcheck: false`

107 add number and long text answer

---

app/views/form-designer/edit-page.html

CHANGED: 
"For a short answer of up to x characters"
TO:
"For a short answer"
AND CHANGED: 
"For longer answers of up to x characters"
TO:
"For a longer answer"
WHY:
Because even if we have an max limit, I don't think it's helpful to say what it is here as it will be very high.
CHANGED:
"The answer will be checked to make sure it's in the numeric format"
TO:
"Requires a numerical answer"
WHY:
shorter
CHANGED:
"To collect an address with separate input fields - line 1, line 2, town or city, county and postcode"
TO:
"To collect an address with separate fields for line 1, line 2, town or city, county and postcode"
WHY:
'input fields' is maybe a bit jargony.
CHANGED: 
"The answer will be checked to make sure it's in the format of an email address"
TO:
"Requires an answer in the format of an …

Updated Edit page hint text

---

app/data/returning-session-data-defaults-a11y.js
app/data/returning-session-data-defaults.js
app/routes.js
app/views/form-builder-prototypes.html
app/views/form-designer/create-form.html
app/views/form-designer/form-list-a11y.html
app/views/form-designer/form-list.html

Things that I've changed:
- update Insolvency Service form to the new first form - Amendment form: redundancy claim for holiday pay
- update the "Take your pet abroad" form
- added a link to both forms from the ["Form builder prototypes" page](https://forms-prototypes.london.cloudapps.digital/form-builder-prototypes)
- fixed intentional typos across both forms
- added "Completed" status checks to the Task list page for Summary (CYA)/Declaration screen
- added "Completed" status checks to the Task list page for Confirmation screen
- removed extra (non working) links from the GOV.UK Forms - Your forms page
- updated edit link on the GOV.UK Forms - Your forms page to go to the new Task list page instead of directly into the Form overview page

Set return data for testing and add links to journeys

---

app/data/returning-session-data-defaults-a11y.js
app/data/returning-session-data-defaults.js
app/data/session-data-defaults.js
app/routes.js
app/views/form-designer/edit-check-answers-page.html
app/views/form-designer/edit-confirmation-page.html
app/views/form-designer/form-create-a-form.html

- updated caption to pull through form name - no longer shows page type name for example, "Check your answers"
- changed H1 on the edit page: "Form summary page"
- made H1 on the edit page static - the user is no longer able to change this
- added new explainer content to page to help users understand what the page is for and does
- added new inset text to give a usable example to form creator so they have a better idea of what could be included here
- made the "Declaration" text area mandatory giving an error if empty: "Enter a declaration" @hannahkc to review
- removed the line rule from the screen as this doesn't align with other pages in the service (should be used more sparingly)
- updated green button action to take user back to "Create a form" task list page
- added new secondary …

112 design and content for the check your answers page and declaration

---

app/assets/sass/application.scss
app/data/returning-session-data-defaults.js
app/routes.js
app/views/form-designer/are-you-sure-you-want-to-edit-live-questions.html
app/views/form-designer/create-form.html
app/views/form-designer/form-index.html

Added return journey for option 1 agreed with developers
See [MURAL screens](https://app.mural.co/t/gaap0347/m/gaap0347/1652697480711/fa60d6e36c472088d3c49ea4a7e7fc5b1d8186d4?wid=0-1659519691366)
I have included the interrupt page, but this can be a nice to have when we put into development if there is time.
May need to revisit some of the linking once we update live links and privacy journeys

New return journey for option 1 added

---

app/routes.js
app/views/form-designer/are-you-sure-you-want-to-edit-live-questions.html
app/views/form-designer/create-form.html
app/views/form-designer/form-is-live.html
app/views/form-designer/make-your-form-live.html

Based on [Mural mockups](https://app.mural.co/t/gaap0347/m/gaap0347/1652697480711/fa60d6e36c472088d3c49ea4a7e7fc5b1d8186d4?wid=0-1659349599412)
Add a link to make form live page
Small tweak to the logic to allow access to making form live link a bit faster
Removed `form` tag
Add make form live and form is live pages
When you make the form live it changes the form status to Live and all related tags
Add errors to pages

Add make form live journey

---

app/views/form-designer/edit-page.html

I've made three small changes: 
1. 
Removed full stop on ‘Question text’ hint because it already has a question mark.
2. 
CHANGED:
You can use hint text if you need to explain the format the answer should be in, or where to find the information you’ve asked for.
TO:
Use hint text to help people answer the question. For example, to explain the format the answer should be in, or where to find the information you’ve asked for.
WHY:
More descriptive. This needed to be better since we shortened the label to just 'Hint text'.  
3.
CHANGED:
Requires a specific day, month and year
TO:
Requires a day, month and year
WHY:
To avoid people thinking it will only accept one specific date.

'Edit question' page content tweaks

---

app/data/returning-session-data-defaults.js
app/routes.js
app/views/form-designer/create-form.html
app/views/form-designer/make-your-form-live.html
app/views/form-designer/page-preview-new-tab.html
app/views/form-designer/provide-link-to-privacy-information.html
app/views/layout-govuk-form-preview.html

[Trello card](https://trello.com/c/5hf54nQf)
[Design based on Mural area](https://app.mural.co/t/gaap0347/m/gaap0347/1652697480711/fa60d6e36c472088d3c49ea4a7e7fc5b1d8186d4?wid=0-1659598224882)
As a form creator, I need to create a privacy notice for my form, so the people completing it know why we're asking for the information how we will process it, and to meet GDPR.
- The department that uses GOV.UK Forms is the ‘data controller’ and they have to provide information about the data they collect and how they manage it to meet the requirements of GDPR.
**If we** ask the form creator to provide a link to privacy information for a form before they can make a form live
**then** they will be able to provide a ink to privacy information for their form
**then** including privacy notice will …

121 design how to get form creators to provide a url for a page with privacy information for their form

---

app/views/form-designer/edit-confirmation-page.html

Following usability testing in sprint 9 I have: 
- Made the label text more descriptive. And clearer that it is information for people completing the form.
- Added 'example' heading to make it clearer what the example is.
Also want to remove the character count but not sure how to do that so I need help!

Content updates to 'what happens next' page

---

app/views/form-designer/completed-forms-email/confirmation-code-sent.html
app/views/form-designer/completed-forms-email/set-completed-forms-email.html

Content updates following usability testing to make this content more descriptive and clearer. Have provided more reasoning for asking for the email address and the need to confirm it.

Content updates to setting email address

---

app/views/form-designer/create-form.html
app/views/form-designer/edit-check-answers-page.html

Content improvement based on findings from usability testing in sprint 9. Changes have been made to: 
- focus on providing declaration content (that’s the action) rather than on checking answers - made the task list link text, heading and content more specific
- make it clearer that the declaration is for people who are completing the form to agree to
- add an example heading to make it clearer what the example is, and to be consistent with the pattern on the 'what happens next' page.
- make the label text more descriptive and clear

Content updates for declaration

---

app/views/form-designer/page-preview-new-tab.html

Small content updates.
"Get help with this form" is more specific than 'get help with your form' and they might not think of it as 'their' form. 
Changed 'Contact us online' to just 'Online' as I don't think there's a need to say 'contact us' before each of the channel types.

Updates to content in contact info for end users

---

app/routes.js
app/views/form-designer/edit-answer-type.html
app/views/form-designer/edit-page.html

I think I've got this working, it's a little hacky but is able to pull through and edit questions and answer types with no impact to the preview journey

New separate answer type page

---

app/routes.js
app/views/form-designer/check-answers-page-preview-new-tab.html
app/views/form-designer/check-answers-page-preview.html
app/views/form-designer/confirmation-page-preview-new-tab.html
app/views/form-designer/edit-answer-type.html
app/views/form-designer/edit-page.html
app/views/form-designer/page-preview-new-tab.html
app/views/form-designer/page-preview.html

This PR covers off the [designs from MURAL](https://app.mural.co/t/gaap0347/m/gaap0347/1652082094071/bd86d8544291bd649aa003aa1c9a94576e730bc6?wid=0-1661519078192)
New options added to answer type:
- One or more selected options from a list
- Yes or no
Add another option pattern added to Edit question page. This should allow user testing to add and remove multiple answers. Useful testing will be to check if users think the options save upon typing into the box or if they need to click a "Save..." button.
Other things fixed:
- removed "Preview this question in a new tab" link from Edit question page above in page preview
- hide "What happens next" title from confirmation pages if no text has been added to textarea
- update CYA button to reflect if no declaration has been add for example, …

134 form creator can make lists to select from

---

app/views/form-designer/pages/edit-answer-type.html

[
](url)
Adds hint text to number and select options from a list answer types

Add hint text to answer types

---

app/views/form-designer/pages/check-answers/edit.html

Small content updates to declaration content for clarity and style:
- expanding the heading to make it clearer that the declaration is for the people filling in the form
- adding missing positive contractions
These changes have been made in production already.
Trello card: https://trello.com/c/aV6PgFiX/323-content-improvements-to-declaration-page-make-it-clearer-and-more-specific-prototype-and-production

Small content updates to declaration content

---

app/views/form-designer/completed-forms-email/confirmation-code-sent.html

Added 'What you need to do next' heading to this page to highlight to users that there is another step to do to confirm the email address.

Add heading to confirmation code success page

---

app/routes.js
app/views/form-designer/pages/edit-answer-type.html
app/views/form-designer/pages/edit-select-question.html
app/views/form-designer/pages/edit-settings.html
app/views/form-designer/pages/edit.html

[Trello](https://trello.com/c/fYZ69pYs)
We're looking to test an alternative way of creating a select from a list question, where we first let user specify their question and then add a list of options. We want to test if this flow is more intuitive for the users, as we learned from previous rounds of testing that some users were expecting to set their questions first and not the option list.

Change journey for create select from list question

---

app/views/form-designer/pages/check-answers/edit.html

So that it matches what we have in production
Trello:
https://trello.com/c/E6yQ39Ac

Add missing hint text to add declaration page

---

lib/utils.js

This workaround was needed to handle situations where we a form submits data named something like `pages[<n>][<key>]`.
However, in a subsequent commit (96fbeff), the routes that update the pages list were refactored, to make it easier for our designers to maintain [[1]].
I believe that this means that the workaround code in utils is no longer reachable, and can be removed. I have left a warning in case I'm wrong...
[1]: https://gds.slack.com/archives/C030K5706TX/p1678457780289839?thread_ts=1678444323.339829&cid=C030K5706TX

Remove store data workaround

---

app/views/form-designer/pages/edit-settings.html

People have decided to ask for a title in usability sessions even when they've said they don't really need to. So we want to discourage asking for one unless it's really needed. And rather than having examples of some titles - which could suggest there will be a list to select from - we want to highlight that it will be a free text field for people to enter whatever title they prefer.

Improve title hint

---

app/views/form-designer/pages/edit-settings.html
app/views/form-designer/pages/edit.html

In user research we saw that the use of the word ‘field’ can be jarring and confusing for some. Box is a plainer language alternative.
This changes the use of 'field' in both the question and the playback of the question settings on the 'Edit question' page.

Change 'field' to 'box' for name question

---

app/routes.js
app/views/form-designer/pages/additional-guidance.html
app/views/form-designer/pages/check-question.html
app/views/form-designer/pages/edit-BACKUP.html
app/views/form-designer/pages/edit-answer-type.html
app/views/form-designer/pages/edit-select-question.html
app/views/form-designer/pages/edit-settings.html
app/views/form-designer/pages/edit.html
app/views/form-designer/preview/page.html
app/views/form-designer/your-questions.html
app/views/layout-govuk-form-preview.html
package-lock.json
package.json

Some minor updates to align with where build is.
- Added new detailed guidance screen (no way to do a quick preview)
- Also displays and restructures the runner equivalent to match [design system pattern](https://design-system.service.gov.uk/patterns/question-pages/#asking-complex-questions-without-using-hint-text)
- Added new check your question (CYA) screen to question creation journey
Needed to update/add `marked` plugin and overwrite the renderer for this as per instructions for [govuk-markdown plugin](https://github.com/x-govuk/govuk-markdown). 
- the renderer is set in `routes.js` 
```
marked.setOptions({
renderer: new GovukHTMLRenderer()
})
```
Updated back buttons for question creation journey to fix some bugs and match the new journey better, but means using …

New detailed guidance journey created, ready for testing. 

---

package-lock.json
package.json

We've been getting the following error when running our prototype:
```
Error: Cannot find module 'govuk-prototype-kit/node_modules/nunjucks'
```
This PR bumps [@lfdebrux/nunjucks-markdown](https://github.com/lfdebrux/govuk-prototype-kit-nunjucks-markdown-plugin) from 0.0.1 to 0.0.3.
This fixes the nunjucks-markdown tags; version 13.5.0 of govuk-prototype-kit changed the way that package is released, which in turn broke assumptions in @lfdebrux/nunjucks-markdown. Version 0.0.3 of @lfdebrux/nunjucks-markdown has been tested with the latest version of govuk-prototype-kit and works again.

Fix nunjucks-markdown

---

app/assets/sass/application.scss
app/routes.js
app/views/form-designer/name-your-form.html
app/views/form-designer/pages/_routes.js
app/views/form-designer/pages/additional-guidance.html
app/views/form-designer/pages/check-question.html
app/views/form-designer/pages/edit-answer-type.html
app/views/form-designer/pages/edit-select-question.html
app/views/form-designer/pages/edit-settings.html
app/views/form-designer/pages/edit.html
app/views/form-designer/pages/preview-question.html
app/views/form-designer/pages/preview.html
app/views/form-designer/your-questions.html
app/views/layout-unbranded-preview.html
package-lock.json
package.json

https://forms-prototypes-pr-208.herokuapp.com/
- Added new [CTA design work from the Mural](https://app.mural.co/t/gaap0347/m/gaap0347/1698835640099/6343df85f7816e0f9d711bd8dc144cd004ea5bce?wid=0-1699284569672)
- this includes simplifying the save call to actions to be a single action
- added the new next steps to the success banner (Add/Edit next question) 
- updated back links to show the page the user should be taken back to, reducing the likelihood of them just seeing “Back” without context
- Added new “Save and preview” button to “Check your question” page
- Added new “Preview question” page
- includes a <div> showing what the question will look like to the end user minus any back/continue interactions as per the [new preview designs on …

204 2023 12 06 previewing a question during creation

---

app/views/form-designer/pages/_routes.js
app/views/form-designer/pages/check-question.html
app/views/form-designer/pages/edit.html
app/views/form-designer/pages/preview-question.html
app/views/form-designer/pages/preview.html

Added new content for in journey preview screen, depending on answer type chosen by the form creator. 
Trello card: [Prototype: Add specific content for previewing a question for each different answer and input type](https://trello.com/c/D7PIFDZa/1345-prototype-add-specific-content-for-previewing-a-question-for-each-different-answer-and-input-type)
Added new hint text for “Make this question” optional
Trello card: [Prototype: Add optional setting hint text](https://trello.com/c/97pTrzpl/1344-prototype-add-optional-setting-hint-text)
Fixed some issues with the preview pages not loading for checkboxes. 
1. check content to make sure it matches the [agreed content (google doc)](https://docs.google.com/document/d/1QlzCLyoBq0UGqbekcsfnRZEAcZtmlEOUqBN_kYPltHc/edit)
2. check that the content …

2024 01 30 previewing a question unique content

---

app/assets/sass/application.scss
app/routes.js
app/views/form-designer/pages/_routes.js
app/views/form-designer/pages/confirmation/view.html
app/views/form-designer/pages/edit-answer-type.html
app/views/form-designer/pages/preview.html
app/views/form-designer/partials/status-draft-form.html
app/views/form-designer/payment/add-payment-link.html
app/views/form-designer/payment/payment-link-example.html
app/views/form-designer/preview/confirmation.html
app/views/form-designer/preview/page.html

- New add payment link task to task list
- New payment page with 3 version of content length, short, medium and long (linked in the footer)
- Simple validation on URL input, with success messaging
- no content work has been done on these yet
- Updated confirmation screen of the preview your form journey to include blue banner, content and payment CTA
- Added an example mockup of what the GOV.UK Pay payment page would look like for form fillers
- There was an error with adding answer types, but not sure what happened - all working again now
- Issue with fieldset legends not displaying correctly - this has been fixed
[PR Heroku app link](https://forms-prototypes-pr-216.herokuapp.com/)
1. check the content matches agreed content on testing area of [mural …

2024 02 01 payment link testing screens

---

app/views/product-pages/group-admin/grouplanding2.html

The link to 'change your name group' leads to a different group landing page, changing that so that the link is inactive and user remains on that same page

Small change on change the name of the group link
